#!/bin/sh
# Generate a self-signed public/private key pair.
keytool -genkeypair \
  -keystore /app/server.keystore -storepass serverpassword \
  -alias localhost \
  -keyalg RSA -validity 365 -dname "CN=, OU=, O=, L=, ST=, C="
keytool -exportcert \
  -keystore /app/server.keystore -storepass serverpassword \
  -alias localhost \
  -file /app/localhost.cer
keytool -importcert \
  -keystore /app/client.truststore -storepass clientpassword \
  -alias localhost \
  -file /app/localhost.cer \
  -noprompt
# Start the server in a detached screen.
screen -dmS server \
  java \
  -Djavax.net.ssl.keyStore="/app/server.keystore" -Djavax.net.ssl.keyStorePassword="serverpassword" \
  -jar /app/lib/tt-server.jar
# Configure the server.
screen -S server -p 0 -X stuff "add world /app/worlds/$world.json\n"
screen -S server -p 0 -X stuff "add agent $name\n"
screen -S server -p 0 -X stuff "set agent $name password $password\n"
sleep 1
# Start this client in a detached screen.
screen -dmS client \
  java \
  -Djavax.net.ssl.trustStore="/app/client.truststore" -Djavax.net.ssl.trustStorePassword="clientpassword" \
  -cp "/app/lib/*:/app/bin" \
  "$main"
# Start the test client.
java \
  -Djavax.net.ssl.trustStore="/app/client.truststore" -Djavax.net.ssl.trustStorePassword="clientpassword" \
  -jar /app/lib/tt-test-client.jar \
  -world "$world" \
  -player \
  -partner "$name"
